import sqlite3
from tkinter import messagebox
from tkinter import *
win1=Tk()
l=Label(win1,text='username')
l2=Label(win1,text="password")
l.place(x=10,y=10)
l2.place(x=10,y=30)
E1=StringVar()
E2=StringVar()
e1=Entry(textvariable=E1)
e1.place(x=80,y=10)
e2=Entry(textvariable=E2)
e2.place(x=80,y=30)
def d():
    a=E1.get()
    b=E2.get()
    try:
        con=sqlite3.connect("tkdb.db")
        cur=con.cursor()
        cur.execute("create table if not exists t1(username varchar(25),password varchar(45))")
        cur.execute("insert into t1 values(?,?)",(a,b))
        con.commit()
        con.close()
        messagebox.showinfo("app-chat","login success...")
    except:
        messagebox.showerror("app-chat","error in login...")
def d1():
        con=sqlite3.connect("tkdb.db")
        cur=con.cursor()
        cur.execute("select * from t1")
        r=cur.fetchall()
        t=Tk()
        ll=Label(t,text="username    password")
        ll.place(x=10,y=10)
        y1=30
        for i in r:
            l3=Label(t,text=i[0])
            l3.place(x=10,y=y1)
            l4=Label(t,text=i[1])
            l4.place(x=80,y=y1)
            y1+=30
def d2():
    aaa=E1.get()
    con=sqlite3.connect("tkdb.db")
    cur=con.cursor()
    cur.execute("delete from t1 where username=?",(aaa,))
    con.commit()
    con.close()
def d3():
    aaa=E1.get()
    bbb=E2.get()
    con=sqlite3.connect("tkdb.db")
    cur=con.cursor()
    cur.execute("update t1 set password=? where password=?",(bbb,aaa,))
    con.commit()
    con.close()
b1=Button(win1,text="save",command=d)
b1.place(x=50,y=60)
b2=Button(win1,text="view",command=d1)
b2.place(x=50,y=90)
b3=Button(win1,text='delete',command=d2)
b3.place(x=50,y=120)
b4=Button(win1,text='update',command=d3)
b4.place(x=50,y=140)
win1.mainloop()
